### ISSUE TITLE
OSX: get working with homebrew?

### ISSUE THREAD

**Issue by zenspider** [erickguan/ffi-icu#39]
I'm seeing tests fail between linux and OSX, because the apple-supplied version has different formats than newer versions (date:medium specifically).

While poking, I got it working for homebrew (icu4c v 66.1) but I had to add some kinda gross hacks. The newer version has version numbers in the function signatures but the compiled libs do not have that in their filenames... So I added an extra env FFI_ICU_VERSION to make it work.

A more proper fallback would probably involve parsing the version from `icuinfo`... but my hack was cheaper/quicker.

It _seems_ to work fine for what I've tested. Are you interested in such a thing? I can't tell the vitality of this project.

**Comment by matt-cook** [comment]
@zenspider I'm attempting to test w/ icu4c v 69.1. What hacks did you add to use the updated version via homebrew?

**Comment by zenspider** [comment]
19 months later? I can't remember... Basically answers my question as to the vitality of the project and desire for fixes...
